# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: std_msgs/msg/v1/header.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'std_msgs/msg/v1/header.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.builtin_interfaces.msg.v1 import time_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstd_msgs/msg/v1/header.proto\x12\x0fstd_msgs.msg.v1\x1a$builtin_interfaces/msg/v1/time.proto\"J\n\x06Header\x12.\n\x05stamp\x18\x01 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.std_msgs.msg.v1.header_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=87
  _globals['_HEADER']._serialized_end=161
# @@protoc_insertion_point(module_scope)
