# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: std_msgs/msg/v1/multi_array_msgs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'std_msgs/msg/v1/multi_array_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import multi_array_pb2 as std__msgs_dot_msg_dot_v1_dot_multi__array__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&std_msgs/msg/v1/multi_array_msgs.proto\x12\x0fstd_msgs.msg.v1\x1a!std_msgs/msg/v1/multi_array.proto\"T\n\x11\x46loat64MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\"T\n\x11\x46loat32MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"Q\n\x0eInt8MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x05\"R\n\x0fInt16MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x05\"R\n\x0fInt32MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x05\"R\n\x0fInt64MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x03\"R\n\x0fUInt8MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\r\"S\n\x10UInt16MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\r\"S\n\x10UInt32MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\r\"S\n\x10UInt64MultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x04\"Q\n\x0e\x42yteMultiArray\x12\x31\n\x06layout\x18\x01 \x01(\x0b\x32!.std_msgs.msg.v1.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.std_msgs.msg.v1.multi_array_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOAT64MULTIARRAY']._serialized_start=94
  _globals['_FLOAT64MULTIARRAY']._serialized_end=178
  _globals['_FLOAT32MULTIARRAY']._serialized_start=180
  _globals['_FLOAT32MULTIARRAY']._serialized_end=264
  _globals['_INT8MULTIARRAY']._serialized_start=266
  _globals['_INT8MULTIARRAY']._serialized_end=347
  _globals['_INT16MULTIARRAY']._serialized_start=349
  _globals['_INT16MULTIARRAY']._serialized_end=431
  _globals['_INT32MULTIARRAY']._serialized_start=433
  _globals['_INT32MULTIARRAY']._serialized_end=515
  _globals['_INT64MULTIARRAY']._serialized_start=517
  _globals['_INT64MULTIARRAY']._serialized_end=599
  _globals['_UINT8MULTIARRAY']._serialized_start=601
  _globals['_UINT8MULTIARRAY']._serialized_end=683
  _globals['_UINT16MULTIARRAY']._serialized_start=685
  _globals['_UINT16MULTIARRAY']._serialized_end=768
  _globals['_UINT32MULTIARRAY']._serialized_start=770
  _globals['_UINT32MULTIARRAY']._serialized_end=853
  _globals['_UINT64MULTIARRAY']._serialized_start=855
  _globals['_UINT64MULTIARRAY']._serialized_end=938
  _globals['_BYTEMULTIARRAY']._serialized_start=940
  _globals['_BYTEMULTIARRAY']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
