# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: std_msgs/msg/v1/primitives.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'std_msgs/msg/v1/primitives.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n std_msgs/msg/v1/primitives.proto\x12\x0fstd_msgs.msg.v1\"\x14\n\x04\x42ool\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x08\"\x14\n\x04Int8\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x15\n\x05Int16\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x15\n\x05Int32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x15\n\x05Int64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x03\"\x15\n\x05UInt8\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\r\"\x16\n\x06UInt16\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\r\"\x16\n\x06UInt32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\r\"\x16\n\x06UInt64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x04\"\x17\n\x07\x46loat32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\"\x17\n\x07\x46loat64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x01\"\x16\n\x06String\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x14\n\x04\x42yte\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.std_msgs.msg.v1.primitives_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOL']._serialized_start=53
  _globals['_BOOL']._serialized_end=73
  _globals['_INT8']._serialized_start=75
  _globals['_INT8']._serialized_end=95
  _globals['_INT16']._serialized_start=97
  _globals['_INT16']._serialized_end=118
  _globals['_INT32']._serialized_start=120
  _globals['_INT32']._serialized_end=141
  _globals['_INT64']._serialized_start=143
  _globals['_INT64']._serialized_end=164
  _globals['_UINT8']._serialized_start=166
  _globals['_UINT8']._serialized_end=187
  _globals['_UINT16']._serialized_start=189
  _globals['_UINT16']._serialized_end=211
  _globals['_UINT32']._serialized_start=213
  _globals['_UINT32']._serialized_end=235
  _globals['_UINT64']._serialized_start=237
  _globals['_UINT64']._serialized_end=259
  _globals['_FLOAT32']._serialized_start=261
  _globals['_FLOAT32']._serialized_end=284
  _globals['_FLOAT64']._serialized_start=286
  _globals['_FLOAT64']._serialized_end=309
  _globals['_STRING']._serialized_start=311
  _globals['_STRING']._serialized_end=333
  _globals['_BYTE']._serialized_start=335
  _globals['_BYTE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
