# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shape_msgs/msg/v1/solid_primitive.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shape_msgs/msg/v1/solid_primitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import polygon_pb2 as geometry__msgs_dot_msg_dot_v1_dot_polygon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'shape_msgs/msg/v1/solid_primitive.proto\x12\x11shape_msgs.msg.v1\x1a\"geometry_msgs/msg/v1/polygon.proto\"b\n\x0eSolidPrimitive\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x12\n\ndimensions\x18\x02 \x03(\x01\x12.\n\x07polygon\x18\x03 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Polygonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.shape_msgs.msg.v1.solid_primitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLIDPRIMITIVE']._serialized_start=98
  _globals['_SOLIDPRIMITIVE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
