# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/admittance_controller_state.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'control_msgs/msg/v1/admittance_controller_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import multi_array_msgs_pb2 as std__msgs_dot_msg_dot_v1_dot_multi__array__msgs__pb2
from robot_bus.geometry_msgs.msg.v1 import stamped_pb2 as geometry__msgs_dot_msg_dot_v1_dot_stamped__pb2
from robot_bus.sensor_msgs.msg.v1 import joint_state_pb2 as sensor__msgs_dot_msg_dot_v1_dot_joint__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5control_msgs/msg/v1/admittance_controller_state.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a&std_msgs/msg/v1/multi_array_msgs.proto\x1a\"geometry_msgs/msg/v1/stamped.proto\x1a$sensor_msgs/msg/v1/joint_state.proto\"\xf4\x04\n\x19\x41\x64mittanceControllerState\x12\x42\n\x12ref_trans_base_fts\x18\x01 \x01(\x0b\x32&.geometry_msgs.msg.v1.TransformStamped\x12\x39\n\rselected_axes\x18\x02 \x01(\x0b\x32\".std_msgs.msg.v1.Float64MultiArray\x12?\n\x0f\x66t_sensor_frame\x18\x03 \x01(\x0b\x32&.geometry_msgs.msg.v1.TransformStamped\x12\x43\n\x13\x61\x64mittance_position\x18\x04 \x01(\x0b\x32&.geometry_msgs.msg.v1.TransformStamped\x12\x43\n\x17\x61\x64mittance_acceleration\x18\x05 \x01(\x0b\x32\".geometry_msgs.msg.v1.TwistStamped\x12?\n\x13\x61\x64mittance_velocity\x18\x06 \x01(\x0b\x32\".geometry_msgs.msg.v1.TwistStamped\x12\x38\n\x0bwrench_base\x18\x07 \x01(\x0b\x32#.geometry_msgs.msg.v1.WrenchStamped\x12H\n\x18robot_ref_trans_base_fts\x18\x08 \x01(\x0b\x32&.geometry_msgs.msg.v1.TransformStamped\x12\x13\n\x0bjoint_names\x18\t \x03(\t\x12\x33\n\x0bjoint_state\x18\n \x01(\x0b\x32\x1e.sensor_msgs.msg.v1.JointStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.admittance_controller_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADMITTANCECONTROLLERSTATE']._serialized_start=193
  _globals['_ADMITTANCECONTROLLERSTATE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
