# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/joint_jog.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'control_msgs/msg/v1/joint_jog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#control_msgs/msg/v1/joint_jog.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\"\x85\x01\n\x08JointJog\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x15\n\rdisplacements\x18\x03 \x03(\x01\x12\x12\n\nvelocities\x18\x04 \x03(\x01\x12\x10\n\x08\x64uration\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.joint_jog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTJOG']._serialized_start=91
  _globals['_JOINTJOG']._serialized_end=224
# @@protoc_insertion_point(module_scope)
