# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/pid_state.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'control_msgs/msg/v1/pid_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.builtin_interfaces.msg.v1 import duration_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#control_msgs/msg/v1/pid_state.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a(builtin_interfaces/msg/v1/duration.proto\"\x9d\x02\n\x08PidState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x35\n\x08timestep\x18\x02 \x01(\x0b\x32#.builtin_interfaces.msg.v1.Duration\x12\r\n\x05\x65rror\x18\x03 \x01(\x01\x12\x11\n\terror_dot\x18\x04 \x01(\x01\x12\x0f\n\x07p_error\x18\x05 \x01(\x01\x12\x0f\n\x07i_error\x18\x06 \x01(\x01\x12\x0f\n\x07\x64_error\x18\x07 \x01(\x01\x12\x0e\n\x06p_term\x18\x08 \x01(\x01\x12\x0e\n\x06i_term\x18\t \x01(\x01\x12\x0e\n\x06\x64_term\x18\n \x01(\x01\x12\r\n\x05i_max\x18\x0b \x01(\x01\x12\r\n\x05i_min\x18\x0c \x01(\x01\x12\x0e\n\x06output\x18\r \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.pid_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIDSTATE']._serialized_start=133
  _globals['_PIDSTATE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
