# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/single_dof_state.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'control_msgs/msg/v1/single_dof_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*control_msgs/msg/v1/single_dof_state.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\"\x9e\x01\n\x0eSingleDOFState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\treference\x18\x02 \x01(\x01\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\x01\x12\x14\n\x0c\x66\x65\x65\x64\x62\x61\x63k_dot\x18\x04 \x01(\x01\x12\r\n\x05\x65rror\x18\x05 \x01(\x01\x12\x11\n\terror_dot\x18\x06 \x01(\x01\x12\x11\n\ttime_step\x18\x07 \x01(\x01\x12\x0e\n\x06output\x18\x08 \x01(\x01\"t\n\x15SingleDOFStateStamped\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x32\n\x05state\x18\x02 \x01(\x0b\x32#.control_msgs.msg.v1.SingleDOFStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.single_dof_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINGLEDOFSTATE']._serialized_start=98
  _globals['_SINGLEDOFSTATE']._serialized_end=256
  _globals['_SINGLEDOFSTATESTAMPED']._serialized_start=258
  _globals['_SINGLEDOFSTATESTAMPED']._serialized_end=374
# @@protoc_insertion_point(module_scope)
