syntax = "proto3";

package geometry_msgs.v1;

import "std_msgs/v1/header.proto";
import "geometry_msgs/v1/accel_wrench.proto";

// Equivalent to ROS 2 `geometry_msgs/msg/AccelWithCovariance`.
message AccelWithCovariance {
  Accel accel = 1;
  // Row-major 6x6 covariance (36 elements) in ROS 2.
  repeated double covariance = 2;
}

// Equivalent to ROS 2 `geometry_msgs/msg/AccelWithCovarianceStamped`.
message AccelWithCovarianceStamped {
  std_msgs.v1.Header header = 1;
  AccelWithCovariance accel = 2;
}
