//! gRPC / gRPC-Web gateway over the ZeroMQ buses.
//!
//! Enabled with `--features grpc`. Covers message Subscribe, service Call,
//! and action bidirectional Run (GOAL / CANCEL ↔ FEEDBACK / RESULT).

pub mod action;
pub mod message;
pub mod server;
pub mod service;

pub mod pb {
    // Pre-generated by `just gen-rust` into src/grpc/generated/ (gitignored;
    // packaged into the crates.io crate so consumers do not need protoc).
    include!("generated/robot_bus_interface.grpc.v1.rs");
}

pub use action::ActionGatewayService;
pub use message::MessageGatewayService;
pub use server::{serve, serve_with_shutdown, GatewayConfig};
pub use service::ServiceGatewayService;
