//! gRPC / gRPC-Web gateway over the ZeroMQ buses.
//!
//! Enabled with `--features grpc`. Covers message Subscribe / Publish, service
//! Call, and action SendGoal (one GOAL request → FEEDBACK / RESULT stream).

pub mod action;
pub mod message;
pub mod server;
pub mod service;

pub mod pb {
    // Pre-generated by `just gen-rust` into src/generated/…/grpc/v1/ (gitignored;
    // packaged into the crates.io crate so consumers do not need protoc).
    include!("../generated/robot_bus_interface/grpc/v1/mod.inc.rs");
}

pub use action::ActionGatewayService;
pub use message::MessageGatewayService;
pub use server::{GatewayConfig, serve, serve_on_listener, serve_with_shutdown};
pub use service::ServiceGatewayService;
