# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shape_msgs/msg/v1/mesh.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'shape_msgs/msg/v1/mesh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import point_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cshape_msgs/msg/v1/mesh.proto\x12\x11shape_msgs.msg.v1\x1a geometry_msgs/msg/v1/point.proto\"&\n\x0cMeshTriangle\x12\x16\n\x0evertex_indices\x18\x01 \x03(\r\"i\n\x04Mesh\x12\x32\n\ttriangles\x18\x01 \x03(\x0b\x32\x1f.shape_msgs.msg.v1.MeshTriangle\x12-\n\x08vertices\x18\x02 \x03(\x0b\x32\x1b.geometry_msgs.msg.v1.Pointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.shape_msgs.msg.v1.mesh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESHTRIANGLE']._serialized_start=85
  _globals['_MESHTRIANGLE']._serialized_end=123
  _globals['_MESH']._serialized_start=125
  _globals['_MESH']._serialized_end=230
# @@protoc_insertion_point(module_scope)
