use std::env;
use std::path::Path;

fn main() {
    // libzmq uses Advapi32 security APIs on Windows. Recent Rust toolchains no
    // longer link advapi32 via std, so cdylib (maturin) builds fail with
    // LNK2019 for InitializeSecurityDescriptor / SetSecurityDescriptorDacl.
    //
    // Protobuf / gRPC stubs are pre-generated (`just gen-rust`); this build
    // script does not invoke protoc.
    let target = env::var("TARGET").unwrap_or_default();
    if target.contains("windows") {
        println!("cargo:rustc-link-lib=advapi32");
    }

    // Embedded console UI is generated by `just console` (not committed).
    // Fail early when the feature is on but assets are missing.
    if env::var_os("CARGO_FEATURE_CONSOLE").is_some() {
        let index = Path::new("assets/console/index.html");
        println!("cargo:rerun-if-changed=assets/console/index.html");
        if !index.is_file() {
            panic!(
                "console feature enabled but assets/console/index.html is missing.\n\
                 \n\
                 Build the embed once, then re-run cargo:\n\
                   just console\n\
                 (or: cd console && pnpm build && ../scripts/sync_console_assets.sh)\n\
                 \n\
                 For UI hot-reload during development, use `cd console && pnpm dev`\n\
                 (proxies /api to the broker) instead of rebuilding assets every time.\n\
                 Or build without the UI: cargo build --no-default-features --features grpc"
            );
        }
    }
}
