# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: visualization_msgs/msg/v1/image_marker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'visualization_msgs/msg/v1/image_marker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.std_msgs.msg.v1 import color_rgba_pb2 as std__msgs_dot_msg_dot_v1_dot_color__rgba__pb2
from robot_bus.builtin_interfaces.msg.v1 import duration_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_duration__pb2
from robot_bus.geometry_msgs.msg.v1 import point_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,visualization_msgs/msg/v1/image_marker.proto\x12\x19visualization_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a std_msgs/msg/v1/color_rgba.proto\x1a(builtin_interfaces/msg/v1/duration.proto\x1a geometry_msgs/msg/v1/point.proto\"\xb5\x03\n\x0bImageMarker\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\n\n\x02ns\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\x05\x12-\n\x08position\x18\x06 \x01(\x0b\x32\x1b.geometry_msgs.msg.v1.Point\x12\r\n\x05scale\x18\x07 \x01(\x02\x12\x31\n\routline_color\x18\x08 \x01(\x0b\x32\x1a.std_msgs.msg.v1.ColorRGBA\x12\x0e\n\x06\x66illed\x18\t \x01(\r\x12.\n\nfill_color\x18\n \x01(\x0b\x32\x1a.std_msgs.msg.v1.ColorRGBA\x12\x35\n\x08lifetime\x18\x0b \x01(\x0b\x32#.builtin_interfaces.msg.v1.Duration\x12+\n\x06points\x18\x0c \x03(\x0b\x32\x1b.geometry_msgs.msg.v1.Point\x12\x32\n\x0eoutline_colors\x18\r \x03(\x0b\x32\x1a.std_msgs.msg.v1.ColorRGBAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.visualization_msgs.msg.v1.image_marker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEMARKER']._serialized_start=216
  _globals['_IMAGEMARKER']._serialized_end=653
# @@protoc_insertion_point(module_scope)
