//! Generate on-disk (gitignored) prost / tonic stubs for robot-bus.
//!
//! Layout mirrors C++/Python (one file per `.proto`):
//!   `src/generated/<pkg>/{msg|srv|action}/v1/<stem>.rs`
//!   `src/generated/robot_bus_interface/grpc/v1/mod.inc.rs`
//!
//! Prost still compiles by package; we then split the package module into
//! per-proto files and `include!` them back into one Rust module so
//! same-package references keep working. Run via
//! `scripts/generate_rust_msgs.py` / `just gen-rust`.

use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use heck::{ToSnakeCase, ToUpperCamelCase};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .ok_or("tools/gen-msgs must live at <repo>/tools/gen-msgs")?
        .to_path_buf();
    env::set_current_dir(&repo_root)?;

    let proto_root = PathBuf::from("proto");
    let out_root = PathBuf::from("src/generated");
    fs::create_dir_all(&out_root)?;
    clear_generated_tree(&out_root)?;

    let legacy_grpc = PathBuf::from("src/grpc/generated");
    if legacy_grpc.is_dir() {
        fs::remove_dir_all(&legacy_grpc)?;
    }

    let mut all_protos = Vec::new();
    collect_protos(&proto_root, &mut all_protos)?;
    all_protos.sort();

    // package → (rust_type_or_mod_name → proto stem)
    let mut package_type_stems: HashMap<String, HashMap<String, String>> = HashMap::new();
    let msg_protos: Vec<PathBuf> = all_protos
        .iter()
        .filter(|p| !path_is_under(p, "proto/robot_bus_interface/grpc"))
        .cloned()
        .collect();

    for path in &msg_protos {
        let content = fs::read_to_string(path)?;
        let package = parse_package(&content)
            .ok_or_else(|| format!("no package in {}", path.display()))?;
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or("proto stem")?
            .to_string();
        let map = package_type_stems.entry(package).or_default();
        for ty in parse_top_level_types(&content) {
            let rust = to_upper_camel(&ty);
            let snake = rust.to_snake_case();
            map.insert(rust, stem.clone());
            map.insert(snake, stem.clone());
        }
    }

    let tmp = out_root.join(".tmp_prost");
    if tmp.is_dir() {
        fs::remove_dir_all(&tmp)?;
    }
    fs::create_dir_all(&tmp)?;

    prost_build::Config::new()
        .out_dir(&tmp)
        .enable_type_names()
        .extern_path(".google.protobuf.Timestamp", "::prost_types::Timestamp")
        .extern_path(".google.protobuf.Duration", "::prost_types::Duration")
        .compile_protos(&msg_protos, &[proto_root.clone()])?;

    let mut file_count = 0usize;
    for entry in fs::read_dir(&tmp)? {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let file_name = path
            .file_name()
            .and_then(|n| n.to_str())
            .ok_or("stub file name")?;
        let package = file_name.trim_end_matches(".rs").to_string();
        let rel_dir = package_to_rel_dir(&package)?;
        let dest_dir = out_root.join(&rel_dir).join("v1");
        fs::create_dir_all(&dest_dir)?;

        let type_stems = package_type_stems.get(&package).ok_or_else(|| {
            format!("no proto type map for package {package}")
        })?;

        let source = fs::read_to_string(&path)?;
        let items = split_top_level_items(&source)?;
        let mut by_stem: BTreeMap<String, Vec<String>> = BTreeMap::new();
        let mut last_stem: Option<String> = None;

        for item in items {
            let stem = match type_stems.get(&item.name) {
                Some(s) => s.clone(),
                None => last_stem.clone().ok_or_else(|| {
                    format!(
                        "cannot map generated item `{}` in package {package} to a .proto stem",
                        item.name
                    )
                })?,
            };
            last_stem = Some(stem.clone());
            by_stem.entry(stem).or_default().push(item.text);
        }

        let mut includes = String::from("// @generated by tools/gen-msgs — do not edit\n");
        for (stem, chunks) in &by_stem {
            let mut body =
                String::from("// This file is @generated by prost-build (split per .proto).\n");
            for chunk in chunks {
                body.push_str(chunk);
                if !chunk.ends_with('\n') {
                    body.push('\n');
                }
            }
            fs::write(dest_dir.join(format!("{stem}.rs")), body)?;
            includes.push_str(&format!("include!(\"{stem}.rs\");\n"));
            file_count += 1;
        }
        fs::write(dest_dir.join("_includes.rs"), includes)?;
    }
    fs::remove_dir_all(&tmp)?;

    // gRPC gateway stubs (tonic) → src/generated/robot_bus_interface/grpc/v1/
    let grpc_dir = out_root.join("robot_bus_interface/grpc/v1");
    fs::create_dir_all(&grpc_dir)?;
    let gateways = [
        PathBuf::from("proto/robot_bus_interface/grpc/v1/message_gateway.proto"),
        PathBuf::from("proto/robot_bus_interface/grpc/v1/service_gateway.proto"),
        PathBuf::from("proto/robot_bus_interface/grpc/v1/action_gateway.proto"),
    ];
    tonic_prost_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir(&grpc_dir)
        .compile_protos(&gateways, &[proto_root])?;

    let grpc_pkg = grpc_dir.join("robot_bus_interface.grpc.v1.rs");
    let grpc_out = grpc_dir.join("mod.inc.rs");
    if !grpc_pkg.exists() {
        return Err("tonic did not write robot_bus_interface.grpc.v1.rs".into());
    }
    fs::rename(&grpc_pkg, &grpc_out)?;

    println!(
        "generated {file_count} per-proto stub(s) under {}/<pkg>/{{msg|srv|action}}/v1/",
        out_root.display()
    );
    println!("generated grpc stub → {}/", grpc_dir.display());
    Ok(())
}

struct Item {
    name: String,
    text: String,
}

fn to_upper_camel(s: &str) -> String {
    sanitize_identifier(&s.to_upper_camel_case())
}

fn sanitize_identifier(ident: &str) -> String {
    match ident {
        "as" | "break" | "const" | "continue" | "else" | "enum" | "false" | "fn" | "for"
        | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move" | "mut" | "pub"
        | "ref" | "return" | "static" | "struct" | "trait" | "true" | "type" | "unsafe"
        | "use" | "where" | "while" | "dyn" | "abstract" | "become" | "box" | "do" | "final"
        | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield" | "async"
        | "await" | "try" | "gen" => format!("r#{ident}"),
        "_" | "super" | "self" | "Self" | "extern" | "crate" => format!("{ident}_"),
        s if s.starts_with(|c: char| c.is_numeric()) => format!("_{ident}"),
        _ => ident.to_string(),
    }
}

fn package_to_rel_dir(package: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    // sensor_msgs.msg.v1 → sensor_msgs/msg  (v1 becomes the directory we create)
    let parts: Vec<&str> = package.split('.').collect();
    if parts.len() < 3 {
        return Err(format!("unexpected package {package}").into());
    }
    // drop trailing version segment ("v1")
    Ok(parts[..parts.len() - 1].iter().collect())
}

fn split_top_level_items(source: &str) -> Result<Vec<Item>, Box<dyn std::error::Error>> {
    let lines: Vec<&str> = source.lines().collect();
    let mut items = Vec::new();
    let mut i = 0usize;

    // Skip file-level `// ...` header (not doc comments).
    while i < lines.len() {
        let t = lines[i].trim_start();
        if t.is_empty() || (t.starts_with("//") && !t.starts_with("///")) {
            i += 1;
            continue;
        }
        break;
    }

    while i < lines.len() {
        while i < lines.len() && lines[i].trim().is_empty() {
            i += 1;
        }
        if i >= lines.len() {
            break;
        }

        let start = i;
        // Leading docs / attributes (including multi-line #[derive(...)]).
        while i < lines.len() {
            let t = lines[i].trim_start();
            if t.starts_with("///") || t.starts_with("#[") {
                if t.starts_with("#[") && !t.contains(']') {
                    i += 1;
                    while i < lines.len() && !lines[i].contains(']') {
                        i += 1;
                    }
                    if i < lines.len() {
                        i += 1;
                    }
                } else {
                    i += 1;
                }
                continue;
            }
            break;
        }
        if i >= lines.len() {
            return Err("trailing docs/attrs without item".into());
        }

        let header = lines[i].trim_start();
        let name = parse_item_name(header).ok_or_else(|| {
            format!("expected pub struct/enum/mod, got: {}", lines[i])
        })?;

        let mut depth = 0i32;
        let mut seen_brace = false;
        while i < lines.len() {
            for c in lines[i].chars() {
                match c {
                    '{' => {
                        depth += 1;
                        seen_brace = true;
                    }
                    '}' => depth -= 1,
                    _ => {}
                }
            }
            i += 1;
            if seen_brace && depth == 0 {
                break;
            }
        }

        let text = lines[start..i].join("\n") + "\n";
        items.push(Item { name, text });
    }

    Ok(items)
}

fn parse_item_name(header: &str) -> Option<String> {
    let header = header.trim_start();
    for prefix in ["pub struct ", "pub enum ", "pub mod "] {
        if let Some(rest) = header.strip_prefix(prefix) {
            let name = rest
                .split(|c: char| c.is_whitespace() || c == '{' || c == '<' || c == '(')
                .next()
                .unwrap_or("")
                .trim();
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    // `impl ::prost::Name for Imu {` / `impl prost::Name for Foo.Bar {`
    if header.starts_with("impl ") {
        if let Some(rest) = header.split(" for ").nth(1) {
            let name = rest
                .split(|c: char| c.is_whitespace() || c == '{' || c == '<')
                .next()
                .unwrap_or("")
                .trim();
            // Nested: `Parent.Child` → use last segment for stem map lookup.
            let name = name.rsplit('.').next().unwrap_or(name);
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    None
}

fn parse_package(content: &str) -> Option<String> {
    for line in content.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("package ") {
            return Some(rest.trim().trim_end_matches(';').trim().to_string());
        }
    }
    None
}

fn parse_top_level_types(content: &str) -> Vec<String> {
    let mut types = Vec::new();
    let mut depth = 0i32;
    for line in content.lines() {
        let trimmed = line.trim();
        let opens = line.matches('{').count() as i32;
        let closes = line.matches('}').count() as i32;
        if depth == 0 {
            if let Some(name) = trimmed
                .strip_prefix("message ")
                .or_else(|| trimmed.strip_prefix("enum "))
            {
                let name = name
                    .split_whitespace()
                    .next()
                    .unwrap_or("")
                    .trim_end_matches('{')
                    .trim();
                if !name.is_empty() {
                    types.push(name.to_string());
                }
            }
        }
        depth += opens - closes;
        if depth < 0 {
            depth = 0;
        }
    }
    types
}

fn path_is_under(path: &Path, prefix: &str) -> bool {
    path.to_string_lossy().replace('\\', "/").contains(prefix)
}

fn collect_protos(
    dir: &Path,
    out: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_protos(&path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("proto") {
            out.push(path);
        }
    }
    Ok(())
}

fn clear_generated_tree(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if !root.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if name == "mod.rs" {
            continue;
        }
        if path.is_dir() {
            fs::remove_dir_all(path)?;
        } else {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}
