syntax = "proto3";

package nav2_msgs.action.v1;

import "builtin_interfaces/msg/v1/duration.proto";

// Equivalent to ROS 2 `nav2_msgs/action/Spin`.
message SpinGoal {
  float target_yaw = 1;
  builtin_interfaces.msg.v1.Duration time_allowance = 2;
}

message SpinResult {
  builtin_interfaces.msg.v1.Duration total_elapsed_time = 1;
  // uint16 in ROS 2:
  //   NONE=0, UNKNOWN=700, TIMEOUT=701, TF_ERROR=702, COLLISION_AHEAD=703
  uint32 error_code = 2;
  string error_msg = 3;
}

message SpinFeedback {
  float angular_distance_traveled = 1;
}
