//! Markdown reports for `ros2_bridge_perf`.

use crate::config::{MSG_HWM, STRING_LEN, image_height, image_width};
use crate::support::{self, ScenarioResult};

pub(crate) fn write_reports(results: &[ScenarioResult]) -> std::io::Result<()> {
    let env = support::env_summary();
    let zh = render(results, &env, true);
    let en = render(results, &env, false);
    let repo = std::env::current_dir()?;
    std::fs::create_dir_all(repo.join("docs/zh"))?;
    std::fs::create_dir_all(repo.join("docs/en"))?;
    std::fs::write(repo.join("docs/zh/ros2-bridge-perf-report.md"), zh)?;
    std::fs::write(repo.join("docs/en/ros2-bridge-perf-report.md"), en)?;
    println!("wrote docs/zh/ros2-bridge-perf-report.md and docs/en/ros2-bridge-perf-report.md");
    Ok(())
}

fn render(results: &[ScenarioResult], env_lines: &[String], zh: bool) -> String {
    let mut md = String::new();
    if zh {
        md.push_str("[English](../en/ros2-bridge-perf-report.md) | 中文\n\n");
        md.push_str("# ROS 2 Bridge 性能测试报告\n\n");
        md.push_str("由 `just perf-ros2-bridge`（`ros2_bridge_perf`）生成，**不进 CI**。\n\n");
        md.push_str("## 环境\n\n");
    } else {
        md.push_str("English | [中文](../zh/ros2-bridge-perf-report.md)\n\n");
        md.push_str("# ROS 2 Bridge performance report\n\n");
        md.push_str(
            "Generated by `just perf-ros2-bridge` (`ros2_bridge_perf`). **Not a CI gate.**\n\n",
        );
        md.push_str("## Environment\n\n");
    }
    for line in env_lines {
        md.push_str(&format!("- {line}\n"));
    }
    md.push_str(&format!(
        "- Image: {}x{} rgb8\n",
        image_width(),
        image_height()
    ));
    md.push_str(&format!(
        "- String payload: {STRING_LEN} bytes; QoS KeepLast({MSG_HWM}) best_effort\n"
    ));
    if zh {
        md.push_str("\n## 方法\n\n");
        md.push_str("- 进程内 broker + `Ros2Bridge`；ROS 与 bus 各一条 peer。\n");
        md.push_str("- 场景：64B `std_msgs/String`；Image 默认 640×480 rgb8；Trigger / Fibonacci 双向（KeepLast 与 topic 档一致）。\n");
        md.push_str("- 吞吐：限速发送约 1s，二分搜索丢包 ≤ 1% 的最大可持续速率。\n");
        md.push_str("- 延迟：另做限速抽样（发一条等收到再发）。\n\n");
        md.push_str("## 结果\n\n");
    } else {
        md.push_str("\n## Method\n\n");
        md.push_str("- In-process broker + `Ros2Bridge`; one ROS peer and one bus peer.\n");
        md.push_str("- Scenarios: 64B `std_msgs/String`; Image 640×480 rgb8 default; Trigger / Fibonacci both directions (KeepLast matches topic benches).\n");
        md.push_str("- Goodput: paced ~1s trials, binary search max rate with loss ≤ 1%.\n");
        md.push_str("- Latency: separate paced samples (send one, wait, repeat).\n\n");
        md.push_str("## Results\n\n");
    }
    md.push_str("| scenario | sent | recv | pub/s | sub/s | delivery | p50 (µs) | p99 (µs) |\n");
    md.push_str("|----------|------|------|-------|-------|----------|----------|----------|\n");
    for r in results {
        if r.note.is_some() {
            md.push_str(&format!(
                "| {} | — | — | — | — | SKIP: {} |\n",
                r.scenario,
                r.note.as_deref().unwrap_or("")
            ));
        } else {
            md.push_str(&format!(
                "| {} | {} | {} | {:.0} | {:.0} | {:.1}% | {:.0} | {:.0} |\n",
                r.scenario,
                r.sent,
                r.received,
                r.publish_per_s,
                r.subscribe_per_s,
                r.delivery_pct,
                r.latency.p50_us,
                r.latency.p99_us,
            ));
        }
    }
    md.push('\n');
    md
}
