syntax = "proto3";

package diagnostic_msgs.v1;

import "std_msgs/v1/header.proto";
import "diagnostic_msgs/v1/key_value.proto";

// Equivalent to ROS 2 `diagnostic_msgs/msg/DiagnosticStatus`.
// This message holds the status of an individual component of the robot.
message DiagnosticStatus {
  // byte in ROS 2:
  //   OK = 0
  //   WARN = 1
  //   ERROR = 2
  //   STALE = 3
  uint32 level = 1;

  // A description of the test/component reporting.
  string name = 2;

  // A description of the status.
  string message = 3;

  // A hardware unique string.
  string hardware_id = 4;

  // Key-value pairs associated with this status.
  repeated KeyValue values = 5;
}

// Equivalent to ROS 2 `diagnostic_msgs/msg/DiagnosticArray`.
// Used to send diagnostic information about the state of the robot.
message DiagnosticArray {
  std_msgs.v1.Header header = 1;
  repeated DiagnosticStatus status = 2;
}
