syntax = "proto3";

package action_msgs.msg.v1;

import "action_msgs/msg/v1/goal_info.proto";

// Equivalent to ROS 2 `action_msgs/msg/GoalStatus`.
message GoalStatus {
  // int8 in ROS 2:
  //   STATUS_UNKNOWN = 0
  //   STATUS_ACCEPTED = 1
  //   STATUS_EXECUTING = 2
  //   STATUS_CANCELING = 3
  //   STATUS_SUCCEEDED = 4
  //   STATUS_CANCELED = 5
  //   STATUS_ABORTED = 6
  GoalInfo goal_info = 1;
  int32 status = 2;
}

// Equivalent to ROS 2 `action_msgs/msg/GoalStatusArray`.
message GoalStatusArray {
  repeated GoalStatus status_list = 1;
}
