# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/drive_controller_state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'control_msgs/msg/v1/drive_controller_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import twist_pb2 as geometry__msgs_dot_msg_dot_v1_dot_twist__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0control_msgs/msg/v1/drive_controller_state.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a geometry_msgs/msg/v1/twist.proto\"\x8b\x02\n\x1bMecanumDriveControllerState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12!\n\x19\x66ront_left_wheel_velocity\x18\x02 \x01(\x01\x12\"\n\x1a\x66ront_right_wheel_velocity\x18\x03 \x01(\x01\x12 \n\x18\x62\x61\x63k_left_wheel_velocity\x18\x04 \x01(\x01\x12!\n\x19\x62\x61\x63k_right_wheel_velocity\x18\x05 \x01(\x01\x12\x37\n\x12reference_velocity\x18\x06 \x01(\x0b\x32\x1b.geometry_msgs.msg.v1.Twist\"\xe1\x01\n\x18SteeringControllerStatus\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12 \n\x18traction_wheels_position\x18\x02 \x03(\x01\x12 \n\x18traction_wheels_velocity\x18\x03 \x03(\x01\x12\x17\n\x0fsteer_positions\x18\x04 \x03(\x01\x12\x1f\n\x17linear_velocity_command\x18\x05 \x03(\x01\x12\x1e\n\x16steering_angle_command\x18\x06 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.drive_controller_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MECANUMDRIVECONTROLLERSTATE']._serialized_start=138
  _globals['_MECANUMDRIVECONTROLLERSTATE']._serialized_end=405
  _globals['_STEERINGCONTROLLERSTATUS']._serialized_start=408
  _globals['_STEERINGCONTROLLERSTATUS']._serialized_end=633
# @@protoc_insertion_point(module_scope)
