# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_msgs/msg/v1/joint_controller_state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'control_msgs/msg/v1/joint_controller_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0control_msgs/msg/v1/joint_controller_state.proto\x12\x13\x63ontrol_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\"\xfd\x01\n\x14JointControllerState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x11\n\tset_point\x18\x02 \x01(\x01\x12\x15\n\rprocess_value\x18\x03 \x01(\x01\x12\x19\n\x11process_value_dot\x18\x04 \x01(\x01\x12\r\n\x05\x65rror\x18\x05 \x01(\x01\x12\x11\n\ttime_step\x18\x06 \x01(\x01\x12\x0f\n\x07\x63ommand\x18\x07 \x01(\x01\x12\t\n\x01p\x18\x08 \x01(\x01\x12\t\n\x01i\x18\t \x01(\x01\x12\t\n\x01\x64\x18\n \x01(\x01\x12\x0f\n\x07i_clamp\x18\x0b \x01(\x01\x12\x12\n\nantiwindup\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.control_msgs.msg.v1.joint_controller_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTCONTROLLERSTATE']._serialized_start=104
  _globals['_JOINTCONTROLLERSTATE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
