# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/battery_state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sensor_msgs/msg/v1/battery_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&sensor_msgs/msg/v1/battery_state.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\"\x82\x03\n\x0c\x42\x61tteryState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x03 \x01(\x02\x12\x0e\n\x06\x63harge\x18\x04 \x01(\x02\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x02\x12\x17\n\x0f\x64\x65sign_capacity\x18\x06 \x01(\x02\x12\x12\n\npercentage\x18\x07 \x01(\x02\x12\x1b\n\x13power_supply_status\x18\x08 \x01(\r\x12\x1b\n\x13power_supply_health\x18\t \x01(\r\x12\x1f\n\x17power_supply_technology\x18\n \x01(\r\x12\x0f\n\x07present\x18\x0b \x01(\x08\x12\x14\n\x0c\x63\x65ll_voltage\x18\x0c \x03(\x02\x12\x18\n\x10\x63\x65ll_temperature\x18\r \x03(\x02\x12\x10\n\x08location\x18\x0e \x01(\t\x12\x15\n\rserial_number\x18\x0f \x01(\t\x12\x13\n\x0btemperature\x18\x10 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.battery_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTERYSTATE']._serialized_start=93
  _globals['_BATTERYSTATE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
