# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/imu.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sensor_msgs/msg/v1/imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import quaternion_pb2 as geometry__msgs_dot_msg_dot_v1_dot_quaternion__pb2
from robot_bus.geometry_msgs.msg.v1 import vector3_pb2 as geometry__msgs_dot_msg_dot_v1_dot_vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csensor_msgs/msg/v1/imu.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a%geometry_msgs/msg/v1/quaternion.proto\x1a\"geometry_msgs/msg/v1/vector3.proto\"\xc7\x02\n\x03Imu\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x35\n\x0borientation\x18\x02 \x01(\x0b\x32 .geometry_msgs.msg.v1.Quaternion\x12\x1e\n\x16orientation_covariance\x18\x03 \x03(\x01\x12\x37\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12#\n\x1b\x61ngular_velocity_covariance\x18\x05 \x03(\x01\x12:\n\x13linear_acceleration\x18\x06 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12&\n\x1elinear_acceleration_covariance\x18\x07 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMU']._serialized_start=158
  _globals['_IMU']._serialized_end=485
# @@protoc_insertion_point(module_scope)
