syntax = "proto3";

package control_msgs.msg.v1;

import "std_msgs/msg/v1/multi_array_msgs.proto";
import "geometry_msgs/msg/v1/stamped.proto";
import "sensor_msgs/msg/v1/joint_state.proto";

// Equivalent to ROS 2 `control_msgs/msg/AdmittanceControllerState`.
message AdmittanceControllerState {
  geometry_msgs.msg.v1.TransformStamped ref_trans_base_fts = 1;
  std_msgs.msg.v1.Float64MultiArray selected_axes = 2;
  geometry_msgs.msg.v1.TransformStamped ft_sensor_frame = 3;

  geometry_msgs.msg.v1.TransformStamped admittance_position = 4;
  geometry_msgs.msg.v1.TwistStamped admittance_acceleration = 5;
  geometry_msgs.msg.v1.TwistStamped admittance_velocity = 6;
  geometry_msgs.msg.v1.WrenchStamped wrench_base = 7;

  // Transform from "world_frame" to "robot_controller" frame when constrained
  // by joints with position interfaces.
  geometry_msgs.msg.v1.TransformStamped robot_ref_trans_base_fts = 8;

  repeated string joint_names = 9;
  sensor_msgs.msg.v1.JointState joint_state = 10;
}
