syntax = "proto3";

package control_msgs.msg.v1;

import "std_msgs/msg/v1/header.proto";

// Equivalent to ROS 2 `control_msgs/msg/SingleDOFState`.
message SingleDOFState {
  string name = 1;
  double reference = 2;
  double feedback = 3;
  double feedback_dot = 4;
  double error = 5;
  double error_dot = 6;
  double time_step = 7;
  double output = 8;
}

// Equivalent to ROS 2 `control_msgs/msg/SingleDOFStateStamped`.
message SingleDOFStateStamped {
  std_msgs.msg.v1.Header header = 1;
  SingleDOFState state = 2;
}
