# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/msg/v1/grid_cells.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/msg/v1/grid_cells.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import point_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nav_msgs/msg/v1/grid_cells.proto\x12\x0fnav_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a geometry_msgs/msg/v1/point.proto\"\x89\x01\n\tGridCells\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x12\n\ncell_width\x18\x02 \x01(\x02\x12\x13\n\x0b\x63\x65ll_height\x18\x03 \x01(\x02\x12*\n\x05\x63\x65lls\x18\x04 \x03(\x0b\x32\x1b.geometry_msgs.msg.v1.Pointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.msg.v1.grid_cells_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRIDCELLS']._serialized_start=118
  _globals['_GRIDCELLS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
