# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/msg/v1/occupancy_grid.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/msg/v1/occupancy_grid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.builtin_interfaces.msg.v1 import time_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_time__pb2
from robot_bus.geometry_msgs.msg.v1 import pose_pb2 as geometry__msgs_dot_msg_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$nav_msgs/msg/v1/occupancy_grid.proto\x12\x0fnav_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a$builtin_interfaces/msg/v1/time.proto\x1a\x1fgeometry_msgs/msg/v1/pose.proto\"\xa4\x01\n\x0bMapMetaData\x12\x36\n\rmap_load_time\x18\x01 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12\x12\n\nresolution\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12*\n\x06origin\x18\x05 \x01(\x0b\x32\x1a.geometry_msgs.msg.v1.Pose\"r\n\rOccupancyGrid\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12*\n\x04info\x18\x02 \x01(\x0b\x32\x1c.nav_msgs.msg.v1.MapMetaData\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.msg.v1.occupancy_grid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPMETADATA']._serialized_start=159
  _globals['_MAPMETADATA']._serialized_end=323
  _globals['_OCCUPANCYGRID']._serialized_start=325
  _globals['_OCCUPANCYGRID']._serialized_end=439
# @@protoc_insertion_point(module_scope)
