# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/msg/v1/odometry.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/msg/v1/odometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import covariance_pb2 as geometry__msgs_dot_msg_dot_v1_dot_covariance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enav_msgs/msg/v1/odometry.proto\x12\x0fnav_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a%geometry_msgs/msg/v1/covariance.proto\"\xbd\x01\n\x08Odometry\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12\x36\n\x04pose\x18\x03 \x01(\x0b\x32(.geometry_msgs.msg.v1.PoseWithCovariance\x12\x38\n\x05twist\x18\x04 \x01(\x0b\x32).geometry_msgs.msg.v1.TwistWithCovarianceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.msg.v1.odometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ODOMETRY']._serialized_start=121
  _globals['_ODOMETRY']._serialized_end=310
# @@protoc_insertion_point(module_scope)
