syntax = "proto3";

package std_msgs.v1;

import "std_msgs/v1/multi_array.proto";

// Equivalent to ROS 2 `std_msgs/msg/Float64MultiArray`.
message Float64MultiArray {
  MultiArrayLayout layout = 1;
  repeated double data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/Float32MultiArray`.
message Float32MultiArray {
  MultiArrayLayout layout = 1;
  repeated float data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/Int8MultiArray`.
message Int8MultiArray {
  MultiArrayLayout layout = 1;
  repeated int32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/Int16MultiArray`.
message Int16MultiArray {
  MultiArrayLayout layout = 1;
  repeated int32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/Int32MultiArray`.
message Int32MultiArray {
  MultiArrayLayout layout = 1;
  repeated int32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/Int64MultiArray`.
message Int64MultiArray {
  MultiArrayLayout layout = 1;
  repeated int64 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/UInt8MultiArray`.
message UInt8MultiArray {
  MultiArrayLayout layout = 1;
  repeated uint32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/UInt16MultiArray`.
message UInt16MultiArray {
  MultiArrayLayout layout = 1;
  repeated uint32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/UInt32MultiArray`.
message UInt32MultiArray {
  MultiArrayLayout layout = 1;
  repeated uint32 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/UInt64MultiArray`.
message UInt64MultiArray {
  MultiArrayLayout layout = 1;
  repeated uint64 data = 2;
}

// Equivalent to ROS 2 `std_msgs/msg/ByteMultiArray`.
message ByteMultiArray {
  MultiArrayLayout layout = 1;
  bytes data = 2;
}
