GROUP=org.indunet
VERSION_NAME=0.1.1

POM_DESCRIPTION=Standalone Android Kotlin SDK for robot-bus (JNA + librobot_bus_c; topics, services, actions)
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/indunet/robot-bus

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/indunet/robot-bus
POM_SCM_CONNECTION=scm:git:git://github.com/indunet/robot-bus.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/indunet/robot-bus.git

POM_DEVELOPER_ID=deng_ran
POM_DEVELOPER_NAME=deng_ran
POM_DEVELOPER_EMAIL=deng_ran@aliyun.com
POM_DEVELOPER_URL=https://github.com/deng_ran

android.useAndroidX=true
org.gradle.jvmargs=-Xmx2g
kotlin.code.style=official
