# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: visualization_msgs/msg/v1/marker.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'visualization_msgs/msg/v1/marker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.std_msgs.msg.v1 import color_rgba_pb2 as std__msgs_dot_msg_dot_v1_dot_color__rgba__pb2
from robot_bus.builtin_interfaces.msg.v1 import duration_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_duration__pb2
from robot_bus.geometry_msgs.msg.v1 import pose_pb2 as geometry__msgs_dot_msg_dot_v1_dot_pose__pb2
from robot_bus.geometry_msgs.msg.v1 import vector3_pb2 as geometry__msgs_dot_msg_dot_v1_dot_vector3__pb2
from robot_bus.geometry_msgs.msg.v1 import point_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point__pb2
from robot_bus.sensor_msgs.msg.v1 import compressed_image_pb2 as sensor__msgs_dot_msg_dot_v1_dot_compressed__image__pb2
from robot_bus.visualization_msgs.msg.v1 import uv_coordinate_pb2 as visualization__msgs_dot_msg_dot_v1_dot_uv__coordinate__pb2
from robot_bus.visualization_msgs.msg.v1 import mesh_file_pb2 as visualization__msgs_dot_msg_dot_v1_dot_mesh__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&visualization_msgs/msg/v1/marker.proto\x12\x19visualization_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a std_msgs/msg/v1/color_rgba.proto\x1a(builtin_interfaces/msg/v1/duration.proto\x1a\x1fgeometry_msgs/msg/v1/pose.proto\x1a\"geometry_msgs/msg/v1/vector3.proto\x1a geometry_msgs/msg/v1/point.proto\x1a)sensor_msgs/msg/v1/compressed_image.proto\x1a-visualization_msgs/msg/v1/uv_coordinate.proto\x1a)visualization_msgs/msg/v1/mesh_file.proto\"\xa3\x05\n\x06Marker\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\n\n\x02ns\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\x05\x12(\n\x04pose\x18\x06 \x01(\x0b\x32\x1a.geometry_msgs.msg.v1.Pose\x12,\n\x05scale\x18\x07 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12)\n\x05\x63olor\x18\x08 \x01(\x0b\x32\x1a.std_msgs.msg.v1.ColorRGBA\x12\x35\n\x08lifetime\x18\t \x01(\x0b\x32#.builtin_interfaces.msg.v1.Duration\x12\x14\n\x0c\x66rame_locked\x18\n \x01(\x08\x12+\n\x06points\x18\x0b \x03(\x0b\x32\x1b.geometry_msgs.msg.v1.Point\x12*\n\x06\x63olors\x18\x0c \x03(\x0b\x32\x1a.std_msgs.msg.v1.ColorRGBA\x12\x18\n\x10texture_resource\x18\r \x01(\t\x12\x34\n\x07texture\x18\x0e \x01(\x0b\x32#.sensor_msgs.msg.v1.CompressedImage\x12?\n\x0euv_coordinates\x18\x0f \x03(\x0b\x32\'.visualization_msgs.msg.v1.UVCoordinate\x12\x0c\n\x04text\x18\x10 \x01(\t\x12\x15\n\rmesh_resource\x18\x11 \x01(\t\x12\x36\n\tmesh_file\x18\x12 \x01(\x0b\x32#.visualization_msgs.msg.v1.MeshFile\x12#\n\x1bmesh_use_embedded_materials\x18\x13 \x01(\x08\"A\n\x0bMarkerArray\x12\x32\n\x07markers\x18\x01 \x03(\x0b\x32!.visualization_msgs.msg.v1.Markerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.visualization_msgs.msg.v1.marker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKER']._serialized_start=412
  _globals['_MARKER']._serialized_end=1087
  _globals['_MARKERARRAY']._serialized_start=1089
  _globals['_MARKERARRAY']._serialized_end=1154
# @@protoc_insertion_point(module_scope)
