# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/srv/v1/get_plan.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/srv/v1/get_plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import stamped_pb2 as geometry__msgs_dot_msg_dot_v1_dot_stamped__pb2
from robot_bus.nav_msgs.msg.v1 import path_pb2 as nav__msgs_dot_msg_dot_v1_dot_path__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enav_msgs/srv/v1/get_plan.proto\x12\x0fnav_msgs.srv.v1\x1a\"geometry_msgs/msg/v1/stamped.proto\x1a\x1anav_msgs/msg/v1/path.proto\"\x86\x01\n\x0eGetPlanRequest\x12\x30\n\x05start\x18\x01 \x01(\x0b\x32!.geometry_msgs.msg.v1.PoseStamped\x12/\n\x04goal\x18\x02 \x01(\x0b\x32!.geometry_msgs.msg.v1.PoseStamped\x12\x11\n\ttolerance\x18\x03 \x01(\x02\"6\n\x0fGetPlanResponse\x12#\n\x04plan\x18\x01 \x01(\x0b\x32\x15.nav_msgs.msg.v1.Pathb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.srv.v1.get_plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPLANREQUEST']._serialized_start=116
  _globals['_GETPLANREQUEST']._serialized_end=250
  _globals['_GETPLANRESPONSE']._serialized_start=252
  _globals['_GETPLANRESPONSE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
