# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/srv/v1/get_map.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/srv/v1/get_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.nav_msgs.msg.v1 import occupancy_grid_pb2 as nav__msgs_dot_msg_dot_v1_dot_occupancy__grid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnav_msgs/srv/v1/get_map.proto\x12\x0fnav_msgs.srv.v1\x1a$nav_msgs/msg/v1/occupancy_grid.proto\"\x0f\n\rGetMapRequest\"=\n\x0eGetMapResponse\x12+\n\x03map\x18\x01 \x01(\x0b\x32\x1e.nav_msgs.msg.v1.OccupancyGridb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.srv.v1.get_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMAPREQUEST']._serialized_start=88
  _globals['_GETMAPREQUEST']._serialized_end=103
  _globals['_GETMAPRESPONSE']._serialized_start=105
  _globals['_GETMAPRESPONSE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
