# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs/srv/v1/set_map.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav_msgs/srv/v1/set_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.nav_msgs.msg.v1 import occupancy_grid_pb2 as nav__msgs_dot_msg_dot_v1_dot_occupancy__grid__pb2
from robot_bus.geometry_msgs.msg.v1 import stamped_pb2 as geometry__msgs_dot_msg_dot_v1_dot_stamped__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnav_msgs/srv/v1/set_map.proto\x12\x0fnav_msgs.srv.v1\x1a$nav_msgs/msg/v1/occupancy_grid.proto\x1a\"geometry_msgs/msg/v1/stamped.proto\"\x83\x01\n\rSetMapRequest\x12+\n\x03map\x18\x01 \x01(\x0b\x32\x1e.nav_msgs.msg.v1.OccupancyGrid\x12\x45\n\x0cinitial_pose\x18\x02 \x01(\x0b\x32/.geometry_msgs.msg.v1.PoseWithCovarianceStamped\"!\n\x0eSetMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav_msgs.srv.v1.set_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETMAPREQUEST']._serialized_start=125
  _globals['_SETMAPREQUEST']._serialized_end=256
  _globals['_SETMAPRESPONSE']._serialized_start=258
  _globals['_SETMAPRESPONSE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
