syntax = "proto3";

package control_msgs.v1;

import "std_msgs/v1/header.proto";
import "builtin_interfaces/v1/duration.proto";

// Equivalent to ROS 2 `control_msgs/msg/PidState`.
message PidState {
  std_msgs.v1.Header header = 1;
  builtin_interfaces.v1.Duration timestep = 2;

  double error = 3;
  double error_dot = 4;

  double p_error = 5;
  double i_error = 6;
  double d_error = 7;

  double p_term = 8;
  double i_term = 9;
  double d_term = 10;

  double i_max = 11;
  double i_min = 12;

  double output = 13;
}
