# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/multi_dof_joint_state.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'sensor_msgs/msg/v1/multi_dof_joint_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import transform_pb2 as geometry__msgs_dot_msg_dot_v1_dot_transform__pb2
from robot_bus.geometry_msgs.msg.v1 import twist_pb2 as geometry__msgs_dot_msg_dot_v1_dot_twist__pb2
from robot_bus.geometry_msgs.msg.v1 import accel_wrench_pb2 as geometry__msgs_dot_msg_dot_v1_dot_accel__wrench__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.sensor_msgs/msg/v1/multi_dof_joint_state.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a$geometry_msgs/msg/v1/transform.proto\x1a geometry_msgs/msg/v1/twist.proto\x1a\'geometry_msgs/msg/v1/accel_wrench.proto\"\xe1\x01\n\x12MultiDOFJointState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x33\n\ntransforms\x18\x03 \x03(\x0b\x32\x1f.geometry_msgs.msg.v1.Transform\x12*\n\x05twist\x18\x04 \x03(\x0b\x32\x1b.geometry_msgs.msg.v1.Twist\x12,\n\x06wrench\x18\x05 \x03(\x0b\x32\x1c.geometry_msgs.msg.v1.Wrenchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.multi_dof_joint_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MULTIDOFJOINTSTATE']._serialized_start=214
  _globals['_MULTIDOFJOINTSTATE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
