# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/multi_echo_laser_scan.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'sensor_msgs/msg/v1/multi_echo_laser_scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.sensor_msgs/msg/v1/multi_echo_laser_scan.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\"\x1b\n\tLaserEcho\x12\x0e\n\x06\x65\x63hoes\x18\x01 \x03(\x02\"\xb0\x02\n\x12MultiEchoLaserScan\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x16\n\x0etime_increment\x18\x05 \x01(\x02\x12\x11\n\tscan_time\x18\x06 \x01(\x02\x12\x11\n\trange_min\x18\x07 \x01(\x02\x12\x11\n\trange_max\x18\x08 \x01(\x02\x12-\n\x06ranges\x18\t \x03(\x0b\x32\x1d.sensor_msgs.msg.v1.LaserEcho\x12\x32\n\x0bintensities\x18\n \x03(\x0b\x32\x1d.sensor_msgs.msg.v1.LaserEchob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.multi_echo_laser_scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LASERECHO']._serialized_start=100
  _globals['_LASERECHO']._serialized_end=127
  _globals['_MULTIECHOLASERSCAN']._serialized_start=130
  _globals['_MULTIECHOLASERSCAN']._serialized_end=434
# @@protoc_insertion_point(module_scope)
