# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/nav_sat_fix.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'sensor_msgs/msg/v1/nav_sat_fix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.sensor_msgs.msg.v1 import nav_sat_status_pb2 as sensor__msgs_dot_msg_dot_v1_dot_nav__sat__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$sensor_msgs/msg/v1/nav_sat_fix.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a\'sensor_msgs/msg/v1/nav_sat_status.proto\"\xdc\x01\n\tNavSatFix\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x30\n\x06status\x18\x02 \x01(\x0b\x32 .sensor_msgs.msg.v1.NavSatStatus\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\x12\x1b\n\x13position_covariance\x18\x06 \x03(\x01\x12 \n\x18position_covariance_type\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.nav_sat_fix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVSATFIX']._serialized_start=132
  _globals['_NAVSATFIX']._serialized_end=352
# @@protoc_insertion_point(module_scope)
