# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_msgs/msg/v1/point_cloud.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sensor_msgs/msg/v1/point_cloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import point32_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point32__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$sensor_msgs/msg/v1/point_cloud.proto\x12\x12sensor_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a\"geometry_msgs/msg/v1/point32.proto\".\n\x0e\x43hannelFloat32\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"\x9a\x01\n\nPointCloud\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12-\n\x06points\x18\x02 \x03(\x0b\x32\x1d.geometry_msgs.msg.v1.Point32\x12\x34\n\x08\x63hannels\x18\x03 \x03(\x0b\x32\".sensor_msgs.msg.v1.ChannelFloat32b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.sensor_msgs.msg.v1.point_cloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELFLOAT32']._serialized_start=126
  _globals['_CHANNELFLOAT32']._serialized_end=172
  _globals['_POINTCLOUD']._serialized_start=175
  _globals['_POINTCLOUD']._serialized_end=329
# @@protoc_insertion_point(module_scope)
