# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/arrow_primitive.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/arrow_primitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import color_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_color__pb2
from robot_bus.foxglove_msgs.msg.v1 import pose_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*foxglove_msgs/msg/v1/arrow_primitive.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a foxglove_msgs/msg/v1/color.proto\x1a\x1f\x66oxglove_msgs/msg/v1/pose.proto\"\xc0\x01\n\x0e\x41rrowPrimitive\x12(\n\x04pose\x18\x01 \x01(\x0b\x32\x1a.foxglove_msgs.msg.v1.Pose\x12\x14\n\x0cshaft_length\x18\x02 \x01(\x01\x12\x16\n\x0eshaft_diameter\x18\x03 \x01(\x01\x12\x13\n\x0bhead_length\x18\x04 \x01(\x01\x12\x15\n\rhead_diameter\x18\x05 \x01(\x01\x12*\n\x05\x63olor\x18\x06 \x01(\x0b\x32\x1b.foxglove_msgs.msg.v1.Colorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.arrow_primitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARROWPRIMITIVE']._serialized_start=136
  _globals['_ARROWPRIMITIVE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
