# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/line_primitive.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/line_primitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import color_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_color__pb2
from robot_bus.foxglove_msgs.msg.v1 import point3_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_point3__pb2
from robot_bus.foxglove_msgs.msg.v1 import pose_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)foxglove_msgs/msg/v1/line_primitive.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a foxglove_msgs/msg/v1/color.proto\x1a!foxglove_msgs/msg/v1/point3.proto\x1a\x1f\x66oxglove_msgs/msg/v1/pose.proto\"\xeb\x02\n\rLinePrimitive\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.foxglove_msgs.msg.v1.LinePrimitive.Type\x12(\n\x04pose\x18\x02 \x01(\x0b\x32\x1a.foxglove_msgs.msg.v1.Pose\x12\x11\n\tthickness\x18\x03 \x01(\x01\x12\x17\n\x0fscale_invariant\x18\x04 \x01(\x08\x12,\n\x06points\x18\x05 \x03(\x0b\x32\x1c.foxglove_msgs.msg.v1.Point3\x12*\n\x05\x63olor\x18\x06 \x01(\x0b\x32\x1b.foxglove_msgs.msg.v1.Color\x12+\n\x06\x63olors\x18\x07 \x03(\x0b\x32\x1b.foxglove_msgs.msg.v1.Color\x12\x0f\n\x07indices\x18\x08 \x03(\x07\"4\n\x04Type\x12\x0e\n\nLINE_STRIP\x10\x00\x12\r\n\tLINE_LOOP\x10\x01\x12\r\n\tLINE_LIST\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.line_primitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEPRIMITIVE']._serialized_start=170
  _globals['_LINEPRIMITIVE']._serialized_end=533
  _globals['_LINEPRIMITIVE_TYPE']._serialized_start=481
  _globals['_LINEPRIMITIVE_TYPE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
