# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/odometry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/odometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import key_value_pair_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_key__value__pair__pb2
from robot_bus.foxglove_msgs.msg.v1 import pose_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_pose__pb2
from robot_bus.foxglove_msgs.msg.v1 import vector3_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_vector3__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#foxglove_msgs/msg/v1/odometry.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a)foxglove_msgs/msg/v1/key_value_pair.proto\x1a\x1f\x66oxglove_msgs/msg/v1/pose.proto\x1a\"foxglove_msgs/msg/v1/vector3.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n\x08Odometry\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x15\n\rbody_frame_id\x18\x03 \x01(\t\x12(\n\x04pose\x18\x04 \x01(\x0b\x32\x1a.foxglove_msgs.msg.v1.Pose\x12;\n\x0flinear_velocity\x18\x05 \x01(\x0b\x32\x1d.foxglove_msgs.msg.v1.Vector3H\x00\x88\x01\x01\x12<\n\x10\x61ngular_velocity\x18\x06 \x01(\x0b\x32\x1d.foxglove_msgs.msg.v1.Vector3H\x01\x88\x01\x01\x12\x17\n\x0fpose_covariance\x18\x07 \x03(\x01\x12\x1b\n\x13velocity_covariance\x18\x08 \x03(\x01\x12\x34\n\x08metadata\x18\t \x03(\x0b\x32\".foxglove_msgs.msg.v1.KeyValuePairB\x12\n\x10_linear_velocityB\x13\n\x11_angular_velocityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.odometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ODOMETRY']._serialized_start=207
  _globals['_ODOMETRY']._serialized_end=619
# @@protoc_insertion_point(module_scope)
