# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/scene_entity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/scene_entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import arrow_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_arrow__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import cube_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_cube__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import cylinder_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_cylinder__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import key_value_pair_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_key__value__pair__pb2
from robot_bus.foxglove_msgs.msg.v1 import line_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_line__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import model_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_model__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import sphere_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_sphere__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import text_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_text__primitive__pb2
from robot_bus.foxglove_msgs.msg.v1 import triangle_list_primitive_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_triangle__list__primitive__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'foxglove_msgs/msg/v1/scene_entity.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a*foxglove_msgs/msg/v1/arrow_primitive.proto\x1a)foxglove_msgs/msg/v1/cube_primitive.proto\x1a-foxglove_msgs/msg/v1/cylinder_primitive.proto\x1a)foxglove_msgs/msg/v1/key_value_pair.proto\x1a)foxglove_msgs/msg/v1/line_primitive.proto\x1a*foxglove_msgs/msg/v1/model_primitive.proto\x1a+foxglove_msgs/msg/v1/sphere_primitive.proto\x1a)foxglove_msgs/msg/v1/text_primitive.proto\x1a\x32\x66oxglove_msgs/msg/v1/triangle_list_primitive.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x05\n\x0bSceneEntity\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12+\n\x08lifetime\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x66rame_locked\x18\x05 \x01(\x08\x12\x34\n\x08metadata\x18\x06 \x03(\x0b\x32\".foxglove_msgs.msg.v1.KeyValuePair\x12\x34\n\x06\x61rrows\x18\x07 \x03(\x0b\x32$.foxglove_msgs.msg.v1.ArrowPrimitive\x12\x32\n\x05\x63ubes\x18\x08 \x03(\x0b\x32#.foxglove_msgs.msg.v1.CubePrimitive\x12\x36\n\x07spheres\x18\t \x03(\x0b\x32%.foxglove_msgs.msg.v1.SpherePrimitive\x12:\n\tcylinders\x18\n \x03(\x0b\x32\'.foxglove_msgs.msg.v1.CylinderPrimitive\x12\x32\n\x05lines\x18\x0b \x03(\x0b\x32#.foxglove_msgs.msg.v1.LinePrimitive\x12>\n\ttriangles\x18\x0c \x03(\x0b\x32+.foxglove_msgs.msg.v1.TriangleListPrimitive\x12\x32\n\x05texts\x18\r \x03(\x0b\x32#.foxglove_msgs.msg.v1.TextPrimitive\x12\x34\n\x06models\x18\x0e \x03(\x0b\x32$.foxglove_msgs.msg.v1.ModelPrimitiveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.scene_entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEENTITY']._serialized_start=535
  _globals['_SCENEENTITY']._serialized_end=1190
# @@protoc_insertion_point(module_scope)
