syntax = "proto3";

package sensor_msgs.msg.v1;

import "std_msgs/msg/v1/header.proto";

// Equivalent to ROS 2 `sensor_msgs/msg/BatteryState`.
message BatteryState {
  std_msgs.msg.v1.Header header = 1;

  // Voltage in Volts. NaN means measurement unavailable.
  float voltage = 2;

  // Negative when discharging [A]. NaN means unavailable.
  float current = 3;

  // Charge in Ah. NaN means unavailable.
  float charge = 4;

  // Capacity in Ah (last full capacity). NaN means unavailable.
  float capacity = 5;

  // Capacity in Ah (design capacity). NaN means unavailable.
  float design_capacity = 6;

  // Charge percentage [0.0 .. 1.0]. NaN means unavailable.
  float percentage = 7;

  // uint8 in ROS 2:
  //   POWER_SUPPLY_STATUS_UNKNOWN = 0
  //   POWER_SUPPLY_STATUS_CHARGING = 1
  //   POWER_SUPPLY_STATUS_DISCHARGING = 2
  //   POWER_SUPPLY_STATUS_NOT_CHARGING = 3
  //   POWER_SUPPLY_STATUS_FULL = 4
  uint32 power_supply_status = 8;

  // uint8 in ROS 2:
  //   POWER_SUPPLY_HEALTH_UNKNOWN = 0
  //   POWER_SUPPLY_HEALTH_GOOD = 1
  //   POWER_SUPPLY_HEALTH_OVERHEAT = 2
  //   POWER_SUPPLY_HEALTH_DEAD = 3
  //   POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4
  //   POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5
  //   POWER_SUPPLY_HEALTH_COLD = 6
  //   POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7
  //   POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8
  uint32 power_supply_health = 9;

  // uint8 in ROS 2:
  //   POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0
  //   POWER_SUPPLY_TECHNOLOGY_NIMH = 1
  //   POWER_SUPPLY_TECHNOLOGY_LION = 2
  //   POWER_SUPPLY_TECHNOLOGY_LIPO = 3
  //   POWER_SUPPLY_TECHNOLOGY_LIFE = 4
  //   POWER_SUPPLY_TECHNOLOGY_NICD = 5
  //   POWER_SUPPLY_TECHNOLOGY_LIMN = 6
  uint32 power_supply_technology = 10;

  bool present = 11;

  // Array of cell voltages [V].
  repeated float cell_voltage = 12;

  // Array of cell temperatures [Celsius].
  repeated float cell_temperature = 13;

  string location = 14;
  string serial_number = 15;

  // Temperature of the battery in Celsius. NaN means unavailable.
  float temperature = 16;
}
