# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf2_msgs/msg/v1/tf_message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf2_msgs/msg/v1/tf_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import stamped_pb2 as geometry__msgs_dot_msg_dot_v1_dot_stamped__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tf2_msgs/msg/v1/tf_message.proto\x12\x0ftf2_msgs.msg.v1\x1a\"geometry_msgs/msg/v1/stamped.proto\"G\n\tTFMessage\x12:\n\ntransforms\x18\x01 \x03(\x0b\x32&.geometry_msgs.msg.v1.TransformStampedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.tf2_msgs.msg.v1.tf_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TFMESSAGE']._serialized_start=89
  _globals['_TFMESSAGE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
