// Adapted from Foxglove schemas (https://github.com/foxglove/foxglove-sdk).
// Official package is `foxglove`; here remapped to project layout.

syntax = "proto3";

import "foxglove_msgs/msg/v1/color.proto";
import "foxglove_msgs/msg/v1/pose.proto";
import "foxglove_msgs/msg/v1/vector3.proto";

package foxglove_msgs.msg.v1;

// A primitive representing a cylinder, elliptic cylinder, or truncated cone
message CylinderPrimitive {
  // Position of the center of the cylinder and orientation of the cylinder. The flat face(s) are perpendicular to the z-axis.
  foxglove_msgs.msg.v1.Pose pose = 1;

  // Size of the cylinder's bounding box
  foxglove_msgs.msg.v1.Vector3 size = 2;

  // 0-1, ratio of the diameter of the cylinder's bottom face (min z) to the bottom of the bounding box
  double bottom_scale = 3;

  // 0-1, ratio of the diameter of the cylinder's top face (max z) to the top of the bounding box
  double top_scale = 4;

  // Color of the cylinder
  foxglove_msgs.msg.v1.Color color = 5;
}
