syntax = "proto3";

package nav2_msgs.v1;

import "std_msgs/v1/header.proto";
import "builtin_interfaces/v1/time.proto";
import "geometry_msgs/v1/pose.proto";

// Equivalent to ROS 2 `nav2_msgs/msg/CostmapMetaData`.
message CostmapMetaData {
  builtin_interfaces.v1.Time map_load_time = 1;
  builtin_interfaces.v1.Time update_time = 2;

  // The map resolution [m/cell].
  float resolution = 3;

  uint32 size_x = 4;
  uint32 size_y = 5;

  // The origin of the map [m, m, rad]. This is the real-world pose of the
  // cell (0,0) in the map.
  geometry_msgs.v1.Pose origin = 6;

  // Name of the layer that generated this costmap.
  string layer = 7;
}

// Equivalent to ROS 2 `nav2_msgs/msg/Costmap`.
message Costmap {
  std_msgs.v1.Header header = 1;
  CostmapMetaData metadata = 2;

  // Cost data in row-major order, starting with (0,0). uint8[] in ROS 2.
  bytes data = 3;
}

// Equivalent to ROS 2 `nav2_msgs/msg/CostmapFilterInfo`.
message CostmapFilterInfo {
  std_msgs.v1.Header header = 1;

  // 0: keepout/lanes filter
  // 1: speed limit filter in % of maximum speed
  // 2: speed limit filter in absolute values (m/s)
  uint32 type = 2;

  string filter_mask_topic = 3;

  // Convert OccGrid data into filter space: space = data * multiplier + base
  float base = 4;
  float multiplier = 5;
}
