#!/usr/bin/env python3
"""Generate TypeScript protobuf modules under bindings/typescript/generated/.

Requires ``protoc`` on PATH (override with env ``PROTOC``) and
``@protobuf-ts/plugin`` installed under ``bindings/typescript``
(``npm install`` there once). Outputs are gitignored; CI and npm publish
run this before pack so the package embeds stubs. Consumers do not need
protoc.

Usage (from repo root)::

  python3 scripts/generate_typescript_msgs.py
  # or: just gen-typescript

Pin ``protoc`` to ``EXPECTED_PROTOC_VERSION`` (same as CI / Python codegen).
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTO_ROOT = ROOT / "proto"
TS_ROOT = ROOT / "bindings" / "typescript"
OUT_ROOT = TS_ROOT / "generated"
PROTOC = os.environ.get("PROTOC", "protoc")

EXPECTED_PROTOC_VERSION = "35.1"

MSG_PACKAGES = (
    "builtin_interfaces",
    "control_msgs",
    "diagnostic_msgs",
    "foxglove_msgs",
    "geometry_msgs",
    "nav2_msgs",
    "nav_msgs",
    "sensor_msgs",
    "shape_msgs",
    "std_msgs",
    "std_srvs",
    "tf2_msgs",
    "trajectory_msgs",
    "unique_identifier_msgs",
    "visualization_msgs",
)

PROTOC_VERSION_RE = re.compile(r"libprotoc\s+(\d+\.\d+(?:\.\d+)?)")


def protoc_version(protoc: str) -> str:
    out = subprocess.check_output([protoc, "--version"], text=True).strip()
    match = PROTOC_VERSION_RE.search(out)
    if not match:
        raise RuntimeError(f"could not parse protoc version from {out!r}")
    return match.group(1)


def ensure_protoc_version(protoc: str) -> None:
    if os.environ.get("ROBOT_BUS_SKIP_PROTOC_VERSION_CHECK") == "1":
        return
    version = protoc_version(protoc)
    if version != EXPECTED_PROTOC_VERSION:
        raise SystemExit(
            f"error: protoc {version} != required {EXPECTED_PROTOC_VERSION}\n"
            f"  Install https://github.com/protocolbuffers/protobuf/releases/tag/v{EXPECTED_PROTOC_VERSION}\n"
            f"  or set PROTOC to that binary. Skip with ROBOT_BUS_SKIP_PROTOC_VERSION_CHECK=1."
        )


def find_protoc_gen_ts() -> Path:
    candidate = TS_ROOT / "node_modules" / ".bin" / "protoc-gen-ts"
    if candidate.is_file() or candidate.with_suffix(".cmd").is_file():
        return candidate
    raise SystemExit(
        f"error: {candidate} not found.\n"
        f"  Run: cd bindings/typescript && npm install"
    )


def collect_protos() -> list[Path]:
    return sorted(PROTO_ROOT.rglob("*.proto"))


def clear_generated() -> None:
    if OUT_ROOT.exists():
        shutil.rmtree(OUT_ROOT)
    OUT_ROOT.mkdir(parents=True, exist_ok=True)


def run_protoc(protos: list[Path], plugin: Path) -> None:
    # client_generic → usable with GrpcWebFetchTransport / RpcTransport.
    ts_opt = ",".join(
        [
            "long_type_string",
            "generate_dependencies",
            "client_generic",
            "server_none",
            "eslint_disable",
            "ts_nocheck",
        ]
    )
    cmd = [
        PROTOC,
        f"--plugin=protoc-gen-ts={plugin}",
        f"--proto_path={PROTO_ROOT}",
        f"--ts_out={ts_opt}:{OUT_ROOT}",
        *[str(p) for p in protos],
    ]
    subprocess.run(cmd, check=True)


def write_index() -> None:
    """Write marker + README for the generated tree."""
    lines = [
        "// Generated by scripts/generate_typescript_msgs.py — do not edit by hand.",
        "// Public import: robot-bus/<pkg>/msg/v1/<file>.js (maps to generated/)",
        "",
    ]
    for pkg in MSG_PACKAGES:
        pkg_dir = OUT_ROOT / pkg
        if pkg_dir.is_dir():
            lines.append(f"// package {pkg}")
    lines.append("")
    (OUT_ROOT / "README.md").write_text(
        "# Generated TypeScript protobuf / gRPC stubs\n\n"
        "Produced by `scripts/generate_typescript_msgs.py` (`just gen-typescript`).\n"
        "Do not edit by hand; re-run after changing `proto/`.\n\n"
        "Public imports (via `package.json` `exports`) omit this directory name:\n\n"
        "```ts\n"
        'import { Imu } from "robot-bus/sensor_msgs/msg/v1/imu.js";\n'
        "// → ./generated/sensor_msgs/msg/v1/imu.js\n"
        "```\n",
        encoding="utf-8",
    )
    (OUT_ROOT / ".generated").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not shutil.which(PROTOC) and not Path(PROTOC).is_file():
        print(f"error: protoc not found ({PROTOC!r})", file=sys.stderr)
        return 1

    ensure_protoc_version(PROTOC)
    plugin = find_protoc_gen_ts()
    protos = collect_protos()
    if not protos:
        print("error: no proto files found", file=sys.stderr)
        return 1

    clear_generated()
    print(f"{PROTOC} ({protoc_version(PROTOC)}) -> {len(protos)} files ...")
    run_protoc(protos, plugin)
    write_index()
    print(f"wrote TypeScript stubs under {OUT_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
