# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav2_msgs/msg/v1/costmap.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav2_msgs/msg/v1/costmap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.builtin_interfaces.msg.v1 import time_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_time__pb2
from robot_bus.geometry_msgs.msg.v1 import pose_pb2 as geometry__msgs_dot_msg_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enav2_msgs/msg/v1/costmap.proto\x12\x10nav2_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a$builtin_interfaces/msg/v1/time.proto\x1a\x1fgeometry_msgs/msg/v1/pose.proto\"\xee\x01\n\x0f\x43ostmapMetaData\x12\x36\n\rmap_load_time\x18\x01 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12\x34\n\x0bupdate_time\x18\x02 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12\x12\n\nresolution\x18\x03 \x01(\x02\x12\x0e\n\x06size_x\x18\x04 \x01(\r\x12\x0e\n\x06size_y\x18\x05 \x01(\r\x12*\n\x06origin\x18\x06 \x01(\x0b\x32\x1a.geometry_msgs.msg.v1.Pose\x12\r\n\x05layer\x18\x07 \x01(\t\"u\n\x07\x43ostmap\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x33\n\x08metadata\x18\x02 \x01(\x0b\x32!.nav2_msgs.msg.v1.CostmapMetaData\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x87\x01\n\x11\x43ostmapFilterInfo\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x19\n\x11\x66ilter_mask_topic\x18\x03 \x01(\t\x12\x0c\n\x04\x62\x61se\x18\x04 \x01(\x02\x12\x12\n\nmultiplier\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav2_msgs.msg.v1.costmap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COSTMAPMETADATA']._serialized_start=154
  _globals['_COSTMAPMETADATA']._serialized_end=392
  _globals['_COSTMAP']._serialized_start=394
  _globals['_COSTMAP']._serialized_end=511
  _globals['_COSTMAPFILTERINFO']._serialized_start=514
  _globals['_COSTMAPFILTERINFO']._serialized_end=649
# @@protoc_insertion_point(module_scope)
