# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav2_msgs/msg/v1/particle_cloud.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nav2_msgs/msg/v1/particle_cloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import pose_pb2 as geometry__msgs_dot_msg_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%nav2_msgs/msg/v1/particle_cloud.proto\x12\x10nav2_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a\x1fgeometry_msgs/msg/v1/pose.proto\"D\n\x08Particle\x12(\n\x04pose\x18\x01 \x01(\x0b\x32\x1a.geometry_msgs.msg.v1.Pose\x12\x0e\n\x06weight\x18\x02 \x01(\x01\"g\n\rParticleCloud\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12-\n\tparticles\x18\x02 \x03(\x0b\x32\x1a.nav2_msgs.msg.v1.Particleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav2_msgs.msg.v1.particle_cloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTICLE']._serialized_start=122
  _globals['_PARTICLE']._serialized_end=190
  _globals['_PARTICLECLOUD']._serialized_start=192
  _globals['_PARTICLECLOUD']._serialized_end=295
# @@protoc_insertion_point(module_scope)
