# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav2_msgs/msg/v1/route.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nav2_msgs/msg/v1/route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import point_pb2 as geometry__msgs_dot_msg_dot_v1_dot_point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cnav2_msgs/msg/v1/route.proto\x12\x10nav2_msgs.msg.v1\x1a geometry_msgs/msg/v1/point.proto\"J\n\tRouteNode\x12\x0e\n\x06nodeid\x18\x01 \x01(\r\x12-\n\x08position\x18\x02 \x01(\x0b\x32\x1b.geometry_msgs.msg.v1.Point\"7\n\tRouteEdge\x12\x0e\n\x06\x65\x64geid\x18\x01 \x01(\r\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0b\n\x03\x65nd\x18\x03 \x01(\r\"(\n\x08\x45\x64geCost\x12\x0e\n\x06\x65\x64geid\x18\x01 \x01(\r\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x02\"_\n\x05Route\x12*\n\x05nodes\x18\x01 \x03(\x0b\x32\x1b.nav2_msgs.msg.v1.RouteNode\x12*\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x1b.nav2_msgs.msg.v1.RouteEdgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav2_msgs.msg.v1.route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTENODE']._serialized_start=84
  _globals['_ROUTENODE']._serialized_end=158
  _globals['_ROUTEEDGE']._serialized_start=160
  _globals['_ROUTEEDGE']._serialized_end=215
  _globals['_EDGECOST']._serialized_start=217
  _globals['_EDGECOST']._serialized_end=257
  _globals['_ROUTE']._serialized_start=259
  _globals['_ROUTE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
