# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/circle_annotation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/circle_annotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import color_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_color__pb2
from robot_bus.foxglove_msgs.msg.v1 import key_value_pair_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_key__value__pair__pb2
from robot_bus.foxglove_msgs.msg.v1 import point2_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_point2__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,foxglove_msgs/msg/v1/circle_annotation.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a foxglove_msgs/msg/v1/color.proto\x1a)foxglove_msgs/msg/v1/key_value_pair.proto\x1a!foxglove_msgs/msg/v1/point2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x02\n\x10\x43ircleAnnotation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x08position\x18\x02 \x01(\x0b\x32\x1c.foxglove_msgs.msg.v1.Point2\x12\x10\n\x08\x64iameter\x18\x03 \x01(\x01\x12\x11\n\tthickness\x18\x04 \x01(\x01\x12/\n\nfill_color\x18\x05 \x01(\x0b\x32\x1b.foxglove_msgs.msg.v1.Color\x12\x32\n\routline_color\x18\x06 \x01(\x0b\x32\x1b.foxglove_msgs.msg.v1.Color\x12\x34\n\x08metadata\x18\x07 \x03(\x0b\x32\".foxglove_msgs.msg.v1.KeyValuePairb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.circle_annotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIRCLEANNOTATION']._serialized_start=216
  _globals['_CIRCLEANNOTATION']._serialized_end=521
# @@protoc_insertion_point(module_scope)
