# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/frame_transform.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'foxglove_msgs/msg/v1/frame_transform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import quaternion_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_quaternion__pb2
from robot_bus.foxglove_msgs.msg.v1 import vector3_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_vector3__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*foxglove_msgs/msg/v1/frame_transform.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a%foxglove_msgs/msg/v1/quaternion.proto\x1a\"foxglove_msgs/msg/v1/vector3.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n\x0e\x46rameTransform\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fparent_frame_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63hild_frame_id\x18\x03 \x01(\t\x12\x32\n\x0btranslation\x18\x04 \x01(\x0b\x32\x1d.foxglove_msgs.msg.v1.Vector3\x12\x32\n\x08rotation\x18\x05 \x01(\x0b\x32 .foxglove_msgs.msg.v1.Quaternionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.frame_transform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETRANSFORM']._serialized_start=177
  _globals['_FRAMETRANSFORM']._serialized_end=393
# @@protoc_insertion_point(module_scope)
