# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/image_annotations.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'foxglove_msgs/msg/v1/image_annotations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import circle_annotation_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_circle__annotation__pb2
from robot_bus.foxglove_msgs.msg.v1 import key_value_pair_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_key__value__pair__pb2
from robot_bus.foxglove_msgs.msg.v1 import points_annotation_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_points__annotation__pb2
from robot_bus.foxglove_msgs.msg.v1 import text_annotation_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_text__annotation__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,foxglove_msgs/msg/v1/image_annotations.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a,foxglove_msgs/msg/v1/circle_annotation.proto\x1a)foxglove_msgs/msg/v1/key_value_pair.proto\x1a,foxglove_msgs/msg/v1/points_annotation.proto\x1a*foxglove_msgs/msg/v1/text_annotation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n\x10ImageAnnotations\x12\x32\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x37\n\x07\x63ircles\x18\x01 \x03(\x0b\x32&.foxglove_msgs.msg.v1.CircleAnnotation\x12\x36\n\x06points\x18\x02 \x03(\x0b\x32&.foxglove_msgs.msg.v1.PointsAnnotation\x12\x33\n\x05texts\x18\x03 \x03(\x0b\x32$.foxglove_msgs.msg.v1.TextAnnotation\x12\x34\n\x08metadata\x18\x04 \x03(\x0b\x32\".foxglove_msgs.msg.v1.KeyValuePairB\x0c\n\n_timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.image_annotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEANNOTATIONS']._serialized_start=283
  _globals['_IMAGEANNOTATIONS']._serialized_end=587
# @@protoc_insertion_point(module_scope)
