# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/location_fix.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/location_fix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import color_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_color__pb2
from robot_bus.foxglove_msgs.msg.v1 import key_value_pair_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_key__value__pair__pb2
from robot_bus.foxglove_msgs.msg.v1 import vector3_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_vector3__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'foxglove_msgs/msg/v1/location_fix.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a foxglove_msgs/msg/v1/color.proto\x1a)foxglove_msgs/msg/v1/key_value_pair.proto\x1a\"foxglove_msgs/msg/v1/vector3.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x04\n\x0bLocationFix\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x07 \x01(\t\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x1b\n\x13position_covariance\x18\x04 \x03(\x01\x12Z\n\x18position_covariance_type\x18\x05 \x01(\x0e\x32\x38.foxglove_msgs.msg.v1.LocationFix.PositionCovarianceType\x12\x14\n\x07heading\x18\n \x01(\x01H\x00\x88\x01\x01\x12\x34\n\x08velocity\x18\x0b \x01(\x0b\x32\x1d.foxglove_msgs.msg.v1.Vector3H\x01\x88\x01\x01\x12/\n\x05\x63olor\x18\x08 \x01(\x0b\x32\x1b.foxglove_msgs.msg.v1.ColorH\x02\x88\x01\x01\x12\x34\n\x08metadata\x18\t \x03(\x0b\x32\".foxglove_msgs.msg.v1.KeyValuePair\"V\n\x16PositionCovarianceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x41PPROXIMATED\x10\x01\x12\x12\n\x0e\x44IAGONAL_KNOWN\x10\x02\x12\t\n\x05KNOWN\x10\x03\x42\n\n\x08_headingB\x0b\n\t_velocityB\x08\n\x06_colorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.location_fix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONFIX']._serialized_start=212
  _globals['_LOCATIONFIX']._serialized_end=768
  _globals['_LOCATIONFIX_POSITIONCOVARIANCETYPE']._serialized_start=647
  _globals['_LOCATIONFIX_POSITIONCOVARIANCETYPE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
