# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/location_fixes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/location_fixes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import location_fix_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_location__fix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)foxglove_msgs/msg/v1/location_fixes.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a\'foxglove_msgs/msg/v1/location_fix.proto\"A\n\rLocationFixes\x12\x30\n\x05\x66ixes\x18\x01 \x03(\x0b\x32!.foxglove_msgs.msg.v1.LocationFixb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.location_fixes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONFIXES']._serialized_start=108
  _globals['_LOCATIONFIXES']._serialized_end=173
# @@protoc_insertion_point(module_scope)
