# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/scene_update.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'foxglove_msgs/msg/v1/scene_update.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.foxglove_msgs.msg.v1 import scene_entity_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_scene__entity__pb2
from robot_bus.foxglove_msgs.msg.v1 import scene_entity_deletion_pb2 as foxglove__msgs_dot_msg_dot_v1_dot_scene__entity__deletion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'foxglove_msgs/msg/v1/scene_update.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a\'foxglove_msgs/msg/v1/scene_entity.proto\x1a\x30\x66oxglove_msgs/msg/v1/scene_entity_deletion.proto\"\x80\x01\n\x0bSceneUpdate\x12<\n\tdeletions\x18\x01 \x03(\x0b\x32).foxglove_msgs.msg.v1.SceneEntityDeletion\x12\x33\n\x08\x65ntities\x18\x02 \x03(\x0b\x32!.foxglove_msgs.msg.v1.SceneEntityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.scene_update_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEUPDATE']._serialized_start=157
  _globals['_SCENEUPDATE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
