# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove_msgs/msg/v1/scene_entity_deletion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove_msgs/msg/v1/scene_entity_deletion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0foxglove_msgs/msg/v1/scene_entity_deletion.proto\x12\x14\x66oxglove_msgs.msg.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n\x13SceneEntityDeletion\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12<\n\x04type\x18\x02 \x01(\x0e\x32..foxglove_msgs.msg.v1.SceneEntityDeletion.Type\x12\n\n\x02id\x18\x03 \x01(\t\" \n\x04Type\x12\x0f\n\x0bMATCHING_ID\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.foxglove_msgs.msg.v1.scene_entity_deletion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEENTITYDELETION']._serialized_start=108
  _globals['_SCENEENTITYDELETION']._serialized_end=284
  _globals['_SCENEENTITYDELETION_TYPE']._serialized_start=252
  _globals['_SCENEENTITYDELETION_TYPE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
