syntax = "proto3";

package sensor_msgs.v1;

import "std_msgs/v1/header.proto";
import "geometry_msgs/v1/vector3.proto";

// Equivalent to ROS 2 `sensor_msgs/msg/MagneticField`.
// Measurement of the Magnetic Field vector at a specific location.
message MagneticField {
  std_msgs.v1.Header header = 1;

  // x, y, z components of the field vector in Tesla.
  geometry_msgs.v1.Vector3 magnetic_field = 2;

  // Row-major about x, y, z axes. Fixed size 9 in ROS 2.
  // If covariance is unknown, first element is set to -1.
  repeated double magnetic_field_covariance = 3;
}
