syntax = "proto3";

package sensor_msgs.v1;

import "std_msgs/v1/header.proto";
import "geometry_msgs/v1/point32.proto";

// Equivalent to ROS 2 `sensor_msgs/msg/ChannelFloat32`.
// Holds the data of one channel for all points in a PointCloud.
message ChannelFloat32 {
  // Common names: "u", "v", "rgb", "intensity", "r", "g", "b", ...
  string name = 1;
  repeated float values = 2;
}

// Equivalent to ROS 2 `sensor_msgs/msg/PointCloud`.
// Prefer PointCloud2 for new interfaces.
message PointCloud {
  std_msgs.v1.Header header = 1;
  repeated geometry_msgs.v1.Point32 points = 2;
  repeated ChannelFloat32 channels = 3;
}
