# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diagnostic_msgs/msg/v1/diagnostic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'diagnostic_msgs/msg/v1/diagnostic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.diagnostic_msgs.msg.v1 import key_value_pb2 as diagnostic__msgs_dot_msg_dot_v1_dot_key__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'diagnostic_msgs/msg/v1/diagnostic.proto\x12\x16\x64iagnostic_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a&diagnostic_msgs/msg/v1/key_value.proto\"\x87\x01\n\x10\x44iagnosticStatus\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bhardware_id\x18\x04 \x01(\t\x12\x30\n\x06values\x18\x05 \x03(\x0b\x32 .diagnostic_msgs.msg.v1.KeyValue\"t\n\x0f\x44iagnosticArray\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x38\n\x06status\x18\x02 \x03(\x0b\x32(.diagnostic_msgs.msg.v1.DiagnosticStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.diagnostic_msgs.msg.v1.diagnostic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIAGNOSTICSTATUS']._serialized_start=138
  _globals['_DIAGNOSTICSTATUS']._serialized_end=273
  _globals['_DIAGNOSTICARRAY']._serialized_start=275
  _globals['_DIAGNOSTICARRAY']._serialized_end=391
# @@protoc_insertion_point(module_scope)
