# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geometry_msgs/msg/v1/accel_wrench.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'geometry_msgs/msg/v1/accel_wrench.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import vector3_pb2 as geometry__msgs_dot_msg_dot_v1_dot_vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'geometry_msgs/msg/v1/accel_wrench.proto\x12\x14geometry_msgs.msg.v1\x1a\"geometry_msgs/msg/v1/vector3.proto\"f\n\x05\x41\x63\x63\x65l\x12-\n\x06linear\x18\x01 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12.\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\"e\n\x06Wrench\x12,\n\x05\x66orce\x18\x01 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12-\n\x06torque\x18\x02 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.geometry_msgs.msg.v1.accel_wrench_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCEL']._serialized_start=101
  _globals['_ACCEL']._serialized_end=203
  _globals['_WRENCH']._serialized_start=205
  _globals['_WRENCH']._serialized_end=306
# @@protoc_insertion_point(module_scope)
