# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geometry_msgs/msg/v1/accel_covariance.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'geometry_msgs/msg/v1/accel_covariance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.std_msgs.msg.v1 import header_pb2 as std__msgs_dot_msg_dot_v1_dot_header__pb2
from robot_bus.geometry_msgs.msg.v1 import accel_wrench_pb2 as geometry__msgs_dot_msg_dot_v1_dot_accel__wrench__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+geometry_msgs/msg/v1/accel_covariance.proto\x12\x14geometry_msgs.msg.v1\x1a\x1cstd_msgs/msg/v1/header.proto\x1a\'geometry_msgs/msg/v1/accel_wrench.proto\"U\n\x13\x41\x63\x63\x65lWithCovariance\x12*\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x0b\x32\x1b.geometry_msgs.msg.v1.Accel\x12\x12\n\ncovariance\x18\x02 \x03(\x01\"\x7f\n\x1a\x41\x63\x63\x65lWithCovarianceStamped\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.std_msgs.msg.v1.Header\x12\x38\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32).geometry_msgs.msg.v1.AccelWithCovarianceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.geometry_msgs.msg.v1.accel_covariance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCELWITHCOVARIANCE']._serialized_start=140
  _globals['_ACCELWITHCOVARIANCE']._serialized_end=225
  _globals['_ACCELWITHCOVARIANCESTAMPED']._serialized_start=227
  _globals['_ACCELWITHCOVARIANCESTAMPED']._serialized_end=354
# @@protoc_insertion_point(module_scope)
