# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geometry_msgs/msg/v1/transform.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'geometry_msgs/msg/v1/transform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.geometry_msgs.msg.v1 import vector3_pb2 as geometry__msgs_dot_msg_dot_v1_dot_vector3__pb2
from robot_bus.geometry_msgs.msg.v1 import quaternion_pb2 as geometry__msgs_dot_msg_dot_v1_dot_quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$geometry_msgs/msg/v1/transform.proto\x12\x14geometry_msgs.msg.v1\x1a\"geometry_msgs/msg/v1/vector3.proto\x1a%geometry_msgs/msg/v1/quaternion.proto\"s\n\tTransform\x12\x32\n\x0btranslation\x18\x01 \x01(\x0b\x32\x1d.geometry_msgs.msg.v1.Vector3\x12\x32\n\x08rotation\x18\x02 \x01(\x0b\x32 .geometry_msgs.msg.v1.Quaternionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.geometry_msgs.msg.v1.transform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFORM']._serialized_start=137
  _globals['_TRANSFORM']._serialized_end=252
# @@protoc_insertion_point(module_scope)
