# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav2_msgs/msg/v1/behavior_tree.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nav2_msgs/msg/v1/behavior_tree.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robot_bus.builtin_interfaces.msg.v1 import time_pb2 as builtin__interfaces_dot_msg_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$nav2_msgs/msg/v1/behavior_tree.proto\x12\x10nav2_msgs.msg.v1\x1a$builtin_interfaces/msg/v1/time.proto\"\x92\x01\n\x18\x42\x65haviorTreeStatusChange\x12\x32\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x17\n\x0fprevious_status\x18\x03 \x01(\t\x12\x16\n\x0e\x63urrent_status\x18\x04 \x01(\t\"\x84\x01\n\x0f\x42\x65haviorTreeLog\x12\x32\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1f.builtin_interfaces.msg.v1.Time\x12=\n\tevent_log\x18\x02 \x03(\x0b\x32*.nav2_msgs.msg.v1.BehaviorTreeStatusChangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_bus.nav2_msgs.msg.v1.behavior_tree_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BEHAVIORTREESTATUSCHANGE']._serialized_start=97
  _globals['_BEHAVIORTREESTATUSCHANGE']._serialized_end=243
  _globals['_BEHAVIORTREELOG']._serialized_start=246
  _globals['_BEHAVIORTREELOG']._serialized_end=378
# @@protoc_insertion_point(module_scope)
